create table products (
    product_id int4 generated by default as identity,
    name varchar(255),
    description varchar(255),
    imgurl varchar(255),
    price float8 not null,
    quantity int4 not null,
    createdDateAndTime timestamp,
    category_id_fk int4,
    primary key (product_id)
)